spring.application.name=Task Manager

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

debug=true
spring.main.banner-mode=console

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-part-count=30

file.upload-dir=file:///media/giappc/01D5ACCB78B5DA20/Task-Management-System